name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYzhjOTRlYjMtMzhjMC00NGMyLTljNGItZTcwYjY0NGRhM2Y4IiwidGVuYW50X2lkIjoiNWM1Njk3MmY4NDQxZGMzZGY1MDM2ODQzYTExZGM5MzVhZmQ2YjliMzY3MGM3MjUwNjc2NGVlOTE5Njg4Y2U4YyIsImludGVybmFsX3NlY3JldCI6IjAyNGY0NDU2LTU1NGYtNDY5YS1iODVhLWJhOWM5Mjc0ODczNSJ9.qN-N5W4h2Ue1OIgX9MD1S8AK78FQe3Pj6h93QBXvC-k"

JWT_SECRET = "Aayushjwt"




